# Generated by Django 4.0 on 2024-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_api', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='Changed_gate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('on time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('Before Time', 'before time')], max_length=20),
        ),
    ]
